sudo: false

language: cpp

branches:
  only:
    - master

addons:
  apt:
    packages: &apt-common
      - cmake

matrix:
  include:
    - env: ARCH=-m32
      compiler: gcc
      addons:
        apt:
          sources: &sources-gcc
            - ubuntu-toolchain-r-test
          packages:
            - *apt-common
            - g++-5-multilib
            - g++-5
    - env: ARCH=-m64
      compiler: gcc
      addons:
        apt:
          sources: *sources-gcc
          packages:
            - *apt-common
            - g++-5
script:
  - mkdir -p build && cd build
  - if [ "$CXX" = "gcc" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - export CFLAGS="${ARCH}" CXXFLAGS="${ARCH}"
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make

notifications:
  email:
    recipients:
      - mateusz@loskot.net
    on_success: change # [always|never|change] # default: change
    on_failure: always # [always|never|change] # default: always
