sudo: false

language: cpp

branches:
  only:
    - master

addons:
  apt:
    packages: &apt-common
      - cmake

matrix:
  include:
    - env: COMPILER=g++-5 ARCH=-m32
      compiler: gcc
      addons:
        apt:
          sources: &sources-gcc
            - ubuntu-toolchain-r-test
          packages:
            - *apt-common
            - g++-5
            - g++-5-multilib
    - env: COMPILER=g++-5 ARCH=-m64
      compiler: gcc
      addons:
        apt:
          sources: *sources-gcc
          packages:
            - *apt-common
            - g++-5
script:
  - mkdir -p build
  - cd build
  - export CXX=${COMPILER}
  - export CXXFLAGS=${ARCH}
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make

notifications:
  email:
    recipients:
      - mateusz@loskot.net
    on_success: change # [always|never|change] # default: change
    on_failure: always # [always|never|change] # default: always
