version: 1.0.{build}

os: Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
  - Release

branches:
  only:
    - master

matrix:
  fast_finish: true

before_build:
  - ps: |
      if ($env:PLATFORM -Match "x64") {
        $G="Visual Studio 14 2015 Win64"
      } else {
        $G="Visual Studio 14 2015"
      }
      Write-Host "Running CMake:" -ForegroundColor Magenta
      cmake.exe -G $G -DCMAKE_BUILD_TYPE:STRING=Release -DBOOST_ROOT=C:/Libraries/boost_1_63_0 $env:APPVEYOR_BUILD_FOLDER
      Write-Host "Running MSBuild:" -ForegroundColor Magenta

build:
  project: string_benchmark.sln
  verbosity: minimal

notifications:
- provider: Email
  to:
  - mateusz@loskot.net
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true